# -*- coding: utf-8 -*-
"""reto_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IddqaCwMYgBX4G7s_ag-4FZLVkls5UVy
"""

elementos = int(input("Cuantos elementos quieres mi bro? "))
numeros_reales= []
for total in range(elementos):
  total = float(input("Ingresa el número, que sea real por favor: "))
  numeros_reales.append(total)

suma_nums: int = 0
for i in numeros_reales:
  suma_nums += i
promedio = (suma_nums/len(numeros_reales))
print("El promedio de " +str(numeros_reales)+ " es " +str(promedio))

elementos = int(input("Cuantos elementos quieres mi bro? "))
numeros_realesa= []
numeros_realesb= []

for total_a in range(elementos):
  total_a = float(input("Ingresa el número para el conjunto a, que sea real por favor: "))
  numeros_realesa.append(total_a)

for total_b in range(elementos):
  total_b = float(input("Ingresa el número para el conjunto b, que sea real por favor: "))
  numeros_realesb.append(total_b)

producto_punto : int = 0
for i in range(elementos):
  producto_punto += (numeros_realesa[i]*numeros_realesb[i])
print("El producto punto de la lista " +str(numeros_realesa)+ " y la lista" +str(numeros_realesb)+ " es " +str(producto_punto))

conjunto= []
ceros= []
def string_int(txt):
     conjunto_descompuesto = [int(i) for i in txt]
     ceros.append(conjunto_descompuesto.count(0))
     return conjunto_descompuesto

elementos = int(input("Cuantos elementos quieres mi bro? "))
for total in range(elementos):
  total = int(input("Ingresa el número, que sea entero por favor: "))
  conjunto.append(int(total))

unir_numeros = ''.join(map(str, conjunto))
numeros_unidos = (unir_numeros)
string_int(numeros_unidos)
print("En el conjunto " +str(conjunto)+ " hay un total de " +str(ceros)+  " ceros")