# -*- coding: utf-8 -*-
"""Reto_10_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQUNu9jmVRo4LKeCj8NukBwvqRuOjFM3
"""

conjunto= []
ceros= []
def string_int(txt):
     conjunto_descompuesto = [int(i) for i in txt]
     ceros.append(conjunto_descompuesto.count(0))
     return conjunto_descompuesto

elementos = int(input("Cuantos elementos quieres mi bro? "))
for total in range(elementos):
  total = int(input("Ingresa el número, que sea entero por favor: "))
  conjunto.append(int(total))

unir_numeros = ''.join(map(str, conjunto))
numeros_unidos = (unir_numeros)
string_int(numeros_unidos)
print("En el conjunto " +str(conjunto)+ " hay un total de " +str(ceros)+  " ceros")