# -*- coding: utf-8 -*-
"""Reto_10_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mX_3kUQ6ax5JAtvawQoAWphWQP6ZJbsP
"""

elementos = int(input("Cuantos elementos quieres mi bro? "))
numeros_realesa= []
numeros_realesb= []

for total_a in range(elementos):
  total_a = float(input("Ingresa el número para el conjunto a, que sea real por favor: "))
  numeros_realesa.append(total_a)

for total_b in range(elementos):
  total_b = float(input("Ingresa el número para el conjunto b, que sea real por favor: "))
  numeros_realesb.append(total_b)

producto_punto : int = 0
for i in range(elementos):
  producto_punto += (numeros_realesa[i]*numeros_realesb[i])
print("El producto punto de la lista " +str(numeros_realesa)+ " y la lista" +str(numeros_realesb)+ " es " +str(producto_punto))